### ISSUE TITLE
custom assembly loading with asp.net core

### ISSUE THREAD

**Issue by afernandes** [thiennn/dynamicLoadingRazorLib#1]
I found this tutorial and hope it can help.
At first it is necessary to implement the class DefaultAssemblyProvider and
register at IoC.

[https://shazwazza.com/post/custom-assembly-loading-with-aspnet-core/](https://shazwazza.com/post/custom-assembly-loading-with-aspnet-core/)

**Comment by thiennn** [comment]
It working now
